spring.application.name=gateway

spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=task_app
spring.datasource.password=task_app_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.schemas=prism
spring.flyway.default-schema=prism
spring.flyway.create-schemas=true

spring.ai.openai.api-key=${OPENAI_API_KEY:placeholder}
spring.ai.openai.base-url=${OPENAI_BASE_URL:https://api.openai.com}
spring.autoconfigure.exclude=\
  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,\
  org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true